### ISSUE TITLE
AttributeError: 'GripperInterface' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by loli11111q** [droid-dataset/droid#17]
WARNING:polymetis.gripper_interface:Metadata unavailable from server.
ERROR:zerorpc.core:
Traceback (most recent call last):
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/zhu/droid/droid/franka/robot.py", line 38, in launch_robot
    self._max_gripper_width = self._gripper.metadata.max_width
AttributeError: 'GripperInterface' object has no attribute 'metadata'
/home/zhu/droid/droid/franka/launch_gripper.sh: line 4: 17424 Killed                  launch_gripper.py gripper=franka_hand
/home/zhu/anaconda3/envs/polymetis-local/bin/launch_robot.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('polymetis==0.2')
/home/zhu/anaconda3/envs/polymetis-local/bin/launch_gripper.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('polymetis==0.2')
Traceback (most recent call last):
  File "/home/zhu/droid/droid/fairo/polymetis/polymetis/python/scripts/launch_robot.py", line 84, in main
    client.run()
  File "/home/zhu/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_client/executable_robot_client.py", line 79, in run
    subprocess.run(
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'env', '"PATH=$PATH"', '/home/zhu/droid/droid/fairo/polymetis/polymetis/build/franka_panda_client', '/tmp/tmpk3l9o1zi']' died with <Signals.SIGKILL: 9>.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
--- Logging error ---
Traceback (most recent call last):
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/home/zhu/droid/droid/fairo/polymetis/polymetis/python/scripts/launch_robot.py", line 59, in cleanup
    log.info(
Message: 'Using sudo to kill subprocess with pid 17455, pgid 17455...'
Arguments: ()
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive robot_client/franka_hardware.yaml in file:///home/zhu/droid/droid/fairo/polymetis/polymetis/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive gripper/franka_hand.yaml in pkg://polymetis.conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)

ip_address: localhost
port: 50051

ERROR:zerorpc.core:
Traceback (most recent call last):
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/zhu/droid/droid/franka/robot.py", line 36, in launch_robot
    self._robot = RobotInterface(ip_address="localhost")
  File "/home/zhu/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 352, in __init__
    super().__init__(*args, **kwargs)
  File "/home/zhu/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 93, in __init__
    else self.grpc_connection.GetRobotClientMetadata(EMPTY)
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1716544316.061056411","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"Socket closed","grpc_status":14}"
>

**Comment by AlexanderKhazatsky** [comment]
This issue usually comes up on the first launch of the server, and goes away on the second, has this been the case for you? Any other information would be helpful.

**Comment by AlexanderKhazatsky** [comment]
Hmm okay, within franka/robot.py, launch_robot(), can you call self._gripper.get_state() and see if there is a max_width value in there?

**Comment by AlexanderKhazatsky** [comment]
You may have an older version of polymetis

**Comment by loli11111q** [comment]
I can't call self._gripper.get_state()  because it need metadata in GripperInterface.My polymetis's version is "v1.0-1251-g0a01a7fa7".I'm not sure if this version is possible.if so,how can i git the latest version?
"
    def __init__(self, ip_address: str = "localhost", port: int = 50052):
        # Connect to server
        self.channel = grpc.insecure_channel(f"{ip_address}:{port}")
        self.grpc_connection = polymetis_pb2_grpc.GripperServerStub(self.channel)

        # Get metadata
        try:
            self.metadata = self.grpc_connection.GetRobotClientMetadata(EMPTY)
        except grpc.RpcError:
            log.warning("Metadata unavailable from server.")
"

**Comment by loli11111q** [comment]
I can't call self._gripper.get_state() because it need metadata in GripperInterface.My polymetis's version is "v1.0-1251-g0a01a7fa7".I'm not sure if this version is possible.if so,how can i git the latest version?

"
def init(self, ip_address: str = "localhost", port: int = 50052):
   # Connect to server
   self.channel = grpc.insecure_channel(f"{ip_address}:{port}")
   self.grpc_connection = polymetis_pb2_grpc.GripperServerStub(self.channel)
   # Get metadata
    try:
        self.metadata = self.grpc_connection.GetRobotClientMetadata(EMPTY)
    except grpc.RpcError:
        log.warning("Metadata unavailable from server.")
"

**Comment by loli11111q** [comment]
I can't call self._gripper.get_state() because it need metadata in GripperInterface.My polymetis's version is "v1.0-1251-g0a01a7fa7".I'm not sure if this version is possible.if so,how can i git the latest version?

"
def init(self, ip_address: str = "localhost", port: int = 50052):
   
   self.channel = grpc.insecure_channel(f"{ip_address}:{port}")
   self.grpc_connection = polymetis_pb2_grpc.GripperServerStub(self.channel)

    try:
        self.metadata = self.grpc_connection.GetRobotClientMetadata(EMPTY)
    except grpc.RpcError:
        log.warning("Metadata unavailable from server.")
"

**Comment by loli11111q** [comment]
I can't call self._gripper.get_state() because it need metadata in GripperInterface.My polymetis's version is "v1.0-1251-g0a01a7fa7".I'm not sure if this version is possible.if so,how can i git the latest version?

`
def init(self, ip_address: str = "localhost", port: int = 50052):
   # Connect to server
   self.channel = grpc.insecure_channel(f"{ip_address}:{port}")
   self.grpc_connection = polymetis_pb2_grpc.GripperServerStub(self.channel)
   # Get metadata
    try:
        self.metadata = self.grpc_connection.GetRobotClientMetadata(EMPTY)
    except grpc.RpcError:
        log.warning("Metadata unavailable from server.")
`

**Comment by loli11111q** [comment]
I can't call self._gripper.get_state() because it need metadata in GripperInterface.My polymetis's version is "v1.0-1251-g0a01a7fa7".I'm not sure if this version is possible.if so,how can i git the latest version?
#Get metadata
try:
    self.metadata = self.grpc_connection.GetRobotClientMetadata(EMPTY)
except grpc.RpcError:
    log.warning("Metadata unavailable from server.")

`

**Comment by AlexanderKhazatsky** [comment]
Hmm okay I have not seen this issue before. Did you set up polymetis using our docker feature or on your own?

**Comment by AlexanderKhazatsky** [comment]
If you didn't and installed on your own, could you try to follow these guidelines?

https://droid-dataset.github.io/droid/software-setup/host-installation.html

**Comment by doyoungkim-ml** [comment]
Same issue here; I followed the exact installation with robot version 5.6.0 and libfranka version 0.13.3.

**Comment by AlexanderKhazatsky** [comment]
Hmm, could you try using 0.9.0 if you have a panda and 0.10.0 if you have an FR3? Alternatively, you could just set fingers length to a fixed value in robot.py and sidestep calling the gripper metadata

**Comment by lidingzhe** [comment]
Same issue here; I followed the exact installation with libfranka version 0.9.0, It's GRPC issue? I check the ip and port of the client and server, Do you know how to solve this issue?
