### ISSUE TITLE
Robot context not valid when calling GetRobotClientMetadata

### ISSUE THREAD

**Issue by doyoungkim-ml** [droid-dataset/droid#31]
Warning: Failed to load 'libtorchrot.so' from CONDA_PREFIX, loading from default build directory instead: '/home/lklab/droid/droid/fairo/polymetis/polymetis/build/torch_isolation/libtorchrot.so'
/home/lklab/anaconda3/envs/polymetis-local/bin/launch_robot.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('polymetis==0.2')
/home/lklab/anaconda3/envs/polymetis-local/bin/launch_gripper.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('polymetis==0.2')
/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive gripper/franka_hand.yaml in pkg://polymetis.conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive robot_client/franka_hardware.yaml in pkg://polymetis.conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Traceback (most recent call last):
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/scripts/launch_robot.py", line 84, in main
    client.run()
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_client/executable_robot_client.py", line 78, in run
    subprocess.run(
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/lklab/droid/droid/fairo/polymetis/polymetis/build/franka_panda_client', '/tmp/tmpjdgq00_2']' died with <Signals.SIGILL: 4>.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/bin/bash: line 1: 26675 Done                    echo robot
     26676 Killed                  | sudo -S bash /home/lklab/droid/droid/franka/launch_robot.sh
ERROR:zerorpc.core:
Traceback (most recent call last):
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/lklab/droid/droid/franka/robot.py", line 36, in launch_robot
    self._robot = RobotInterface(ip_address="localhost")
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 348, in __init__
    super().__init__(*args, **kwargs)
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 89, in __init__
    else self.grpc_connection.GetRobotClientMetadata(EMPTY)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.CANCELLED
	details = "Robot context not valid when calling GetRobotClientMetadata!"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-09-01T19:29:47.059817381+09:00", grpc_status:1, grpc_message:"Robot context not valid when calling GetRobotClientMetadata!"}"
>
/home/lklab/droid/droid/franka/launch_gripper.sh: line 5: 26695 Killed                  launch_gripper.py gripper=franka_hand
/home/lklab/anaconda3/envs/polymetis-local/bin/launch_gripper.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('polymetis==0.2')
/home/lklab/anaconda3/envs/polymetis-local/bin/launch_robot.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('polymetis==0.2')
/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive gripper/franka_hand.yaml in pkg://polymetis.conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive robot_client/franka_hardware.yaml in pkg://polymetis.conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Traceback (most recent call last):
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/scripts/launch_robot.py", line 84, in main
    client.run()
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_client/executable_robot_client.py", line 78, in run
    subprocess.run(
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/lklab/droid/droid/fairo/polymetis/polymetis/build/franka_panda_client', '/tmp/tmprrjhqj8f']' died with <Signals.SIGILL: 4>.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
/bin/bash: line 1: 26740 Done                    echo robot
     26741 Killed                  | sudo -S bash /home/lklab/droid/droid/franka/launch_robot.sh
ERROR:zerorpc.core:
Traceback (most recent call last):
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/lklab/droid/droid/franka/robot.py", line 36, in launch_robot
    self._robot = RobotInterface(ip_address="localhost")
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 348, in __init__
    super().__init__(*args, **kwargs)
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 89, in __init__
    else self.grpc_connection.GetRobotClientMetadata(EMPTY)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.CANCELLED
	details = "Robot context not valid when calling GetRobotClientMetadata!"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Robot context not valid when calling GetRobotClientMetadata!", grpc_status:1, created_time:"2024-09-01T19:29:52.210597655+09:00"}"
>

I am following the installation of [https://droid-dataset.github.io/droid/software-setup/host-installation.html](https://droid-dataset.github.io/droid/software-setup/host-installation.html) and having an error above when testing via python scripts/tests/collect_trajectory.py.

Here's my ping test: 
306 packets transmitted, 306 received, 0% packet loss, time 4512ms
rtt min/avg/max/mdev = 0.186/0.495/2.186/0.423 ms
It seems the libfranka communication_test works well(with success_rate 0.99 ~ 1)

I am using the following libfranka and robot version:
Libfranka version: 0.13.3
Franka robot version: 5.6.0

**Comment by doyoungkim-ml** [comment]
Each time I rerun the script, I get different errors such as
ERROR:zerorpc.core:
Traceback (most recent call last):
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/lklab/droid/droid/franka/robot.py", line 38, in launch_robot
    self._max_gripper_width = self._gripper.metadata.max_width
AttributeError: 'GripperInterface' object has no attribute 'metadata'
or 
ERROR:zerorpc.core:
Traceback (most recent call last):
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/lklab/droid/droid/franka/robot.py", line 36, in launch_robot
    self._robot = RobotInterface(ip_address="localhost")
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 348, in __init__
    super().__init__(*args, **kwargs)
  File "/home/lklab/droid/droid/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 89, in __init__
    else self.grpc_connection.GetRobotClientMetadata(EMPTY)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/lklab/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: connect: Connection refused (111)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-09-01T19:42:33.714930473+09:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: connect: Connection refused (111)"}"
>
Anyone have same issue? I have polymetis version 1251_g0a01a7fa7.

**Comment by kingchou007** [comment]
hey did you solve this?

**Comment by doyoungkim-ml** [comment]
For me it was the problem of the CPU of the NUC. Some of the older versions does not fully support the droid setup. Try checking if the CPU is compatible.

**Comment by duandaxia** [comment]
I got the same error but for me it was because my robot ip was not set the same as in the documentation. There are some yaml files containing robot ip. After changing them, it worked.
