### ISSUE TITLE
timeout error when Testing/Validating Entire Setup

### ISSUE THREAD

**Issue by tsrobcvai** [droid-dataset/droid#33]
**Hi, I followed up on the instructions and found this error in the final test. Is there anyone have some ideas? I appreciate any reply!**

(robot) autostruct-1@autostruct1-Precision-7820-Tower:~/workspace/droid$ python scripts/tests/collect_trajectory.py
Traceback (most recent call last):
  File "/home/autostruct-1/anaconda3/envs/robot/lib/python3.7/site-packages/zerorpc/channel.py", line 255, in recv
    event = self._input_queue.get(timeout=timeout)
  File "src/gevent/queue.py", line 335, in gevent._gevent_cqueue.Queue.get
  File "src/gevent/queue.py", line 350, in gevent._gevent_cqueue.Queue.get
  File "src/gevent/queue.py", line 327, in gevent._gevent_cqueue.Queue._Queue__get_or_peek
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/autostruct-1/anaconda3/envs/robot/lib/python3.7/site-packages/zerorpc/core.py", line 227, in _process_response
    reply_event = bufchan.recv(timeout=timeout)
  File "/home/autostruct-1/anaconda3/envs/robot/lib/python3.7/site-packages/zerorpc/channel.py", line 257, in recv
    raise TimeoutExpired(timeout)
zerorpc.exceptions.TimeoutExpired: timeout after 30s

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/tests/collect_trajectory.py", line 6, in <module>
    env = RobotEnv()
  File "/home/autostruct-1/workspace/droid/droid/robot_env.py", line 38, in __init__
    self._robot = ServerInterface(ip_address=nuc_ip)
  File "/home/autostruct-1/workspace/droid/droid/misc/server_interface.py", line 30, in __init__
    attempt_n_times(func_list, max_attempts=2)
  File "/home/autostruct-1/workspace/droid/droid/misc/server_interface.py", line 13, in attempt_n_times
    [f() for f in function_list]
  File "/home/autostruct-1/workspace/droid/droid/misc/server_interface.py", line 13, in <listcomp>
    [f() for f in function_list]
  File "/home/autostruct-1/workspace/droid/droid/misc/server_interface.py", line 37, in launch_controller
    self.server.launch_controller()
  File "/home/autostruct-1/anaconda3/envs/robot/lib/python3.7/site-packages/zerorpc/core.py", line 278, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/home/autostruct-1/anaconda3/envs/robot/lib/python3.7/site-packages/zerorpc/core.py", line 270, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/home/autostruct-1/anaconda3/envs/robot/lib/python3.7/site-packages/zerorpc/core.py", line 230, in _process_response
    'calling remote method {0}'.format(request_event.name)))
  File "/home/autostruct-1/anaconda3/envs/robot/lib/python3.7/site-packages/zerorpc/core.py", line 224, in raise_error
    raise ex
zerorpc.exceptions.TimeoutExpired: timeout after 30s, when calling remote method launch_controller

**Comment by TritiumR** [comment]
Same problem here. Did you figure out what's wrong?

**Comment by GabrielZH** [comment]
Have you addressed this issue? I got the same one, really annoying.
